version: '3.8'

services:
  baihu:
    image: ghcr.io/engigu/baihu:main
    container_name: baihu
    ports:
      - "8052:8052"
    volumes:
      - ./data:/app/data
      - ./configs:/app/configs
      - ./envs:/app/envs
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
